### ISSUE TITLE
Permission settings for update

### ISSUE THREAD

**Issue by LivelyDesigns** [apprain/apprain-source#1]
appRain Help >> PHP Error
Following PHP Error occured:

mkdir(): Permission denied

Execution History
Check step by step execution history. The execution loop has started from bottom to up

AppException Trace:
#0 [internal function]: userErrorHandler(2, 'mkdir(): Permis...', '/var/www/appRai...', 712, Array)
#1 /var/www/appRain-v-3.0.2/appRain-v-3.0.2/apprain/base/modules/utility.php(712): mkdir('/1388443105', 511)
#2 /var/www/appRain-v-3.0.2/appRain-v-3.0.2/apprain/base/modules/universal/installer.php(181): appRain_Base_Modules_Utility->createDir('/1388443105', 511)
#3 /var/www/appRain-v-3.0.2/appRain-v-3.0.2/apprain/base/modules/universal/installer.php(121): appRain_Base_Modules_Universal_Installer->temporary_extract()
#4 /var/www/appRain-v-3.0.2/appRain-v-3.0.2/component/updatemanager/controllers/updatemanager.php(70): appRain_Base_Modules_Universal_Installer->Install()
#5 [internal function]: updatemanagerController->commitAction()
#6 /var/www/appRain-v-3.0.2/appRain-v-3.0.2/app.php(209): call_user_func_array(Array, Array)
#7 /var/www/appRain-v-3.0.2/appRain-v-3.0.2/app.php(339): App::call(Object(updatemanagerController), 'commitAction', Array)
#8 /var/www/appRain-v-3.0.2/appRain-v-3.0.2/webroot/index.php(46): App::run()
#9 {main}

Disable Error Reporting
Set Debug Mode to "0" (Zero) to disable the error reporting from follwing location:

Login Admin Panel 
|_ Preference 
  |_ Configuration
    |_ Debug Mode
       => Set 0

**Comment by apprain** [comment]
Issue has been take care of in new version. Alos, you have to check the user permission to be able to create new directory.
