### ISSUE TITLE
page add panel in cross site scripting vulnerability

### ISSUE THREAD

**Issue by ismailtasdelen** [apprain/apprain-source#6]
Hello Development Team,

ystem info: [Include appRain version, operating system name, and other relevant details]

appRain | License Key 0123456789101112 | Version 4.0.4
Steps to reproduce:

   1. I just tried to run JavaScript code. --> http://localhost/appRain/page/manage-static-pages/update/13
   2. "><img src=x onerror=alert('ismailtasdelen')> tried and worked.

Screenshot : 

![screenshot from 2018-07-18 11-44-01](https://user-images.githubusercontent.com/15425071/42870395-6d2a6ed2-8a80-11e8-8a83-fdde9287d05e.png)
![screenshot from 2018-07-18 11-43-14](https://user-images.githubusercontent.com/15425071/42870396-6d4d16bc-8a80-11e8-9d81-4ccf12253b0f.png)
![screenshot from 2018-07-18 11-42-50](https://user-images.githubusercontent.com/15425071/42870397-6d6ef6ec-8a80-11e8-83b4-897c72d0c2b2.png)

Payload : "><img src=x onerror=alert('ismailtasdelen')>

Thanks

**Comment by apprain** [comment]
You are correct, From admin you can add javascript with your on liability, But if you like to purify it then there is saperate extension to remove javascript. 

The value can be added with adminsion previlige only.
